import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'
import { createAdminClient } from '@/utils/supabase/admin'

/**
 * Generate final brand book PDF
 * This is a simplified version - in production would use pdf-lib or similar
 * For MVP, we'll create a JSON export that can be formatted later
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { brandAssetId } = await req.json()

    if (!brandAssetId) {
      return NextResponse.json({ error: 'brandAssetId required' }, { status: 400 })
    }

    const supabaseAdmin = createAdminClient()

    const { data: brand } = await supabaseAdmin
      .from('property_brand_assets')
      .select('*')
      .eq('id', brandAssetId)
      .single()

    if (!brand) {
      return NextResponse.json({ error: 'Brand asset not found' }, { status: 404 })
    }

    // Verify all 12 sections are approved
    const requiredSections = [
      'section_1_introduction',
      'section_2_positioning',
      'section_3_target_audience',
      'section_4_personas',
      'section_5_name_story',
      'section_6_logo',
      'section_7_typography',
      'section_8_colors',
      'section_9_design_elements',
      'section_10_photo_yep',
      'section_11_photo_nope',
      'section_12_implementation'
    ]

    const missingSection = requiredSections.find(section => !brand[section])
    if (missingSection) {
      return NextResponse.json({ 
        error: 'Not all sections approved', 
        missingSection 
      }, { status: 400 })
    }

    // For MVP: Create comprehensive JSON export
    // In production: Generate actual PDF with pdf-lib
    const brandBook = {
      metadata: {
        brandName: brand.section_5_name_story?.name,
        generatedAt: new Date().toISOString(),
        generatedBy: user.id,
        propertyId: brand.property_id
      },
      sections: {
        cover: {
          brandName: brand.section_5_name_story?.name,
          tagline: brand.section_5_name_story?.tagline,
          logo: brand.section_6_logo?.primary_url
        },
        introduction: brand.section_1_introduction,
        positioning: brand.section_2_positioning,
        targetAudience: brand.section_3_target_audience,
        personas: brand.section_4_personas,
        nameStory: brand.section_5_name_story,
        logo: brand.section_6_logo,
        typography: brand.section_7_typography,
        colors: brand.section_8_colors,
        designElements: brand.section_9_design_elements,
        photoGuidelines: {
          yep: brand.section_10_photo_yep,
          nope: brand.section_11_photo_nope
        },
        implementation: brand.section_12_implementation
      }
    }

    // Save JSON to Supabase Storage
    const fileName = `${brand.property_id}/brand-book-${Date.now()}.json`
    const { data: uploadData, error: uploadError } = await supabaseAdmin.storage
      .from('brand-assets')
      .upload(fileName, JSON.stringify(brandBook, null, 2), {
        contentType: 'application/json',
        upsert: true
      })

    if (uploadError) throw uploadError

    const { data: urlData } = supabaseAdmin.storage
      .from('brand-assets')
      .getPublicUrl(fileName)

    // Update brand asset with PDF URL
    await supabaseAdmin
      .from('property_brand_assets')
      .update({
        brand_book_pdf_url: urlData.publicUrl,
        pdf_generated_at: new Date().toISOString(),
        generation_status: 'complete'
      })
      .eq('id', brandAssetId)

    // Also save to knowledge base
    const brandDocument = `
# ${brand.section_5_name_story?.name} Brand Book

## Positioning
${brand.section_2_positioning?.statement}

${brand.section_2_positioning?.rationale}

## Target Audience
${brand.section_3_target_audience?.primary}

Demographics: ${JSON.stringify(brand.section_3_target_audience?.demographics)}
Psychographics: ${brand.section_3_target_audience?.psychographics?.join(', ')}

## Brand Story
${brand.section_5_name_story?.story}

## Visual Identity
Primary Color: ${brand.section_8_colors?.primary?.hex}
Typography: ${brand.section_7_typography?.headline?.font}

## Photo Guidelines
${brand.section_10_photo_yep?.description}

Criteria: ${brand.section_10_photo_yep?.criteria?.join(', ')}

---
Generated by BrandForge AI
`

    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
    await fetch(`${baseUrl}/api/documents/ingest`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        content: brandDocument,
        metadata: {
          source: 'BrandForge Brand Book',
          type: 'brand_guidelines',
          brandAssetId: brand.id
        },
        propertyId: brand.property_id
      })
    })

    return NextResponse.json({
      success: true,
      pdfUrl: urlData.publicUrl,
      brandBookData: brandBook
    })

  } catch (error) {
    console.error('PDF Generation Error:', error)
    return NextResponse.json({ 
      error: 'PDF generation failed', 
      details: error instanceof Error ? error.message : 'Unknown error' 
    }, { status: 500 })
  }
}


