-- =============================================
-- SITEFORGE AGENTIC SYSTEM DATABASE SCHEMA
-- Complete schema for agentic website generation
-- Created: December 16, 2025
-- =============================================

-- ============================================================================
-- PROPERTY WEBSITES TABLE
-- Stores generated website metadata, blueprints, and agentic outputs
-- ============================================================================
CREATE TABLE IF NOT EXISTS property_websites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid REFERENCES properties(id) ON DELETE CASCADE NOT NULL,
  org_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  
  -- WordPress deployment info
  wp_url text,
  wp_admin_url text,
  wp_instance_id text UNIQUE,
  wp_credentials jsonb, -- { "username": "admin", "password": "..." }
  
  -- Generation tracking
  generation_status text DEFAULT 'queued', 
  -- Status values: 'queued', 'analyzing_brand', 'planning_architecture', 
  --                'creating_design', 'planning_photos', 'generating_content',
  --                'executing_photos', 'validating_quality', 'ready_for_preview',
  --                'deploying', 'complete', 'failed', 'deploy_failed'
  generation_progress int DEFAULT 0, -- 0-100
  current_step text,
  error_message text,
  
  -- Brand intelligence used
  brand_source text, -- 'brandforge', 'knowledge_base', 'generated', 'hybrid'
  brand_confidence numeric(3,2), -- 0.0 to 1.0
  
  -- AGENTIC SYSTEM OUTPUTS (NEW - December 16, 2025)
  blueprint jsonb, -- Complete SiteBlueprint from Orchestrator
  -- Structure: { version, propertyId, pages, brandContext, architecture, 
  --              designSystem, photoManifest, qualityReport, agentLogs }
  
  -- Legacy fields (kept for backward compatibility)
  site_architecture jsonb, -- ArchitectureProposal from Architecture Agent
  pages_generated jsonb, -- GeneratedPage[] from Content Agent
  assets_manifest jsonb, -- PhotoManifest from Photo Agent
  
  -- Blueprint versioning (for conversational editing)
  site_blueprint_version int DEFAULT 1,
  site_blueprint_updated_at timestamptz,
  
  -- Generation input (conversation mode)
  generation_input jsonb, -- { prompt, conversation, preferences }
  
  -- Performance metrics
  generation_started_at timestamptz,
  generation_completed_at timestamptz,
  generation_duration_seconds int,
  deployed_at timestamptz,
  
  -- Analytics (for future tracking)
  page_views int DEFAULT 0,
  tour_requests int DEFAULT 0,
  conversion_rate numeric(5,2),
  
  -- Versioning (for A/B testing and rollback)
  version int DEFAULT 1,
  previous_version_id uuid REFERENCES property_websites(id) ON DELETE SET NULL,
  
  -- User preferences used for generation
  user_preferences jsonb, -- { style, emphasis, ctaPriority }
  
  -- Timestamps
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for property_websites
CREATE INDEX IF NOT EXISTS idx_property_websites_property ON property_websites(property_id);
CREATE INDEX IF NOT EXISTS idx_property_websites_org ON property_websites(org_id);
CREATE INDEX IF NOT EXISTS idx_property_websites_status ON property_websites(generation_status);
CREATE INDEX IF NOT EXISTS idx_property_websites_created ON property_websites(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_property_websites_version ON property_websites(property_id, version DESC);
CREATE INDEX IF NOT EXISTS idx_property_websites_wp_instance ON property_websites(wp_instance_id) 
  WHERE wp_instance_id IS NOT NULL;

-- ============================================================================
-- WEBSITE ASSETS TABLE  
-- Stores images, videos, and other media files used in websites
-- ============================================================================
CREATE TABLE IF NOT EXISTS website_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id uuid REFERENCES property_websites(id) ON DELETE CASCADE NOT NULL,
  
  asset_type text NOT NULL, 
  -- Values: 'logo', 'hero_image', 'amenity_photo', 'lifestyle_photo', 
  --         'floorplan_image', 'icon', 'video', 'pdf'
  
  source text NOT NULL, 
  -- Values: 'uploaded', 'brandforge', 'generated', 'stock', 'property'
  
  file_url text NOT NULL,
  file_size_bytes bigint, -- in bytes
  mime_type text,
  
  -- WordPress integration
  wp_media_id int, -- WordPress media library ID after upload
  
  -- Metadata
  alt_text text,
  caption text,
  usage_context jsonb, -- { page, section, position, image_index, category }
  
  -- Optimization tracking
  optimized boolean DEFAULT false,
  original_url text, -- URL before optimization
  
  -- Agentic system metadata (NEW)
  generation_prompt text, -- If generated by Photo Agent
  quality_score numeric(3,1), -- 0.0-10.0 from Photo Agent analysis
  brand_alignment_score numeric(3,1), -- 0.0-10.0 from Photo Agent
  
  created_at timestamptz DEFAULT now()
);

-- Indexes for website_assets
CREATE INDEX IF NOT EXISTS idx_website_assets_website ON website_assets(website_id);
CREATE INDEX IF NOT EXISTS idx_website_assets_type ON website_assets(asset_type);
CREATE INDEX IF NOT EXISTS idx_website_assets_source ON website_assets(source);
CREATE INDEX IF NOT EXISTS idx_website_assets_wp_media ON website_assets(wp_media_id) 
  WHERE wp_media_id IS NOT NULL;

-- ============================================================================
-- SITEFORGE JOBS TABLE
-- Tracks async generation jobs for monitoring and debugging
-- ============================================================================
CREATE TABLE IF NOT EXISTS siteforge_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id uuid REFERENCES property_websites(id) ON DELETE CASCADE NOT NULL,
  
  job_type text NOT NULL, 
  -- Values: 'full_generation', 'regenerate_page', 'update_content', 
  --         'deploy_changes', 'edit_section', 'generate_photos'
  
  status text DEFAULT 'queued',
  -- Values: 'queued', 'processing', 'complete', 'failed'
  
  input_params jsonb, -- Original request parameters
  output_data jsonb, -- Results/artifacts from agents
  error_details jsonb, -- Error info if failed
  
  -- Agentic system tracking (NEW)
  agent_logs jsonb, -- Array of { agent, action, timestamp, duration }
  
  -- Retry logic
  attempts int DEFAULT 0,
  max_attempts int DEFAULT 3,
  
  -- Timing
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Indexes for siteforge_jobs
CREATE INDEX IF NOT EXISTS idx_siteforge_jobs_website ON siteforge_jobs(website_id);
CREATE INDEX IF NOT EXISTS idx_siteforge_jobs_status ON siteforge_jobs(status);
CREATE INDEX IF NOT EXISTS idx_siteforge_jobs_type ON siteforge_jobs(job_type);
CREATE INDEX IF NOT EXISTS idx_siteforge_jobs_created ON siteforge_jobs(created_at DESC);

-- ============================================================================
-- SITEFORGE BLUEPRINT VERSIONS TABLE (NEW)
-- Stores version history for conversational editing and rollback
-- ============================================================================
CREATE TABLE IF NOT EXISTS siteforge_blueprint_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id uuid REFERENCES property_websites(id) ON DELETE CASCADE NOT NULL,
  version int NOT NULL,
  
  -- Complete blueprint snapshot
  blueprint jsonb NOT NULL,
  
  -- What changed in this version
  changes_summary text,
  edit_intent text, -- User's editing intent if this was an edit
  patches_applied jsonb, -- Array of BlueprintPatchOperation
  
  -- Quality at this version
  quality_score numeric(5,2),
  
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz DEFAULT now(),
  
  UNIQUE(website_id, version)
);

CREATE INDEX IF NOT EXISTS idx_blueprint_versions_website ON siteforge_blueprint_versions(website_id, version DESC);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Ensures users can only access their organization's websites
-- ============================================================================

ALTER TABLE property_websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE website_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE siteforge_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE siteforge_blueprint_versions ENABLE ROW LEVEL SECURITY;

-- Property Websites Policies
CREATE POLICY "Users view their org property websites"
ON property_websites FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

CREATE POLICY "Users manage their org property websites"
ON property_websites FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

-- Service role policies for background processing
CREATE POLICY "Service role full access to property_websites" 
ON property_websites FOR ALL USING (auth.role() = 'service_role');

-- Website Assets Policies
CREATE POLICY "Users view their org website assets"
ON website_assets FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN property_websites ON property_websites.id = website_assets.website_id
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

CREATE POLICY "Users manage their org website assets"
ON website_assets FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN property_websites ON property_websites.id = website_assets.website_id
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

CREATE POLICY "Service role full access to website_assets" 
ON website_assets FOR ALL USING (auth.role() = 'service_role');

-- SiteForge Jobs Policies
CREATE POLICY "Users view their org siteforge jobs"
ON siteforge_jobs FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN property_websites ON property_websites.id = siteforge_jobs.website_id
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

CREATE POLICY "Service role full access to siteforge_jobs" 
ON siteforge_jobs FOR ALL USING (auth.role() = 'service_role');

-- Blueprint Versions Policies
CREATE POLICY "Users view their org blueprint versions"
ON siteforge_blueprint_versions FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles
    JOIN property_websites ON property_websites.id = siteforge_blueprint_versions.website_id
    JOIN properties ON properties.id = property_websites.property_id
    WHERE profiles.id = auth.uid()
    AND profiles.org_id = properties.org_id
  )
);

CREATE POLICY "Service role full access to blueprint versions" 
ON siteforge_blueprint_versions FOR ALL USING (auth.role() = 'service_role');

-- ============================================================================
-- TRIGGERS
-- Automatically update timestamps and maintain data consistency
-- ============================================================================

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_property_websites_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Update property_websites.updated_at on every update
DROP TRIGGER IF EXISTS trigger_property_websites_updated_at ON property_websites;
CREATE TRIGGER trigger_property_websites_updated_at
  BEFORE UPDATE ON property_websites
  FOR EACH ROW
  EXECUTE FUNCTION update_property_websites_updated_at();

-- Function to auto-populate org_id from property
CREATE OR REPLACE FUNCTION set_property_website_org_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    SELECT org_id INTO NEW.org_id
    FROM properties
    WHERE id = NEW.property_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Auto-set org_id for RLS
DROP TRIGGER IF EXISTS trigger_set_website_org_id ON property_websites;
CREATE TRIGGER trigger_set_website_org_id
  BEFORE INSERT ON property_websites
  FOR EACH ROW
  EXECUTE FUNCTION set_property_website_org_id();

-- ============================================================================
-- HELPER VIEWS
-- ============================================================================

-- View: Website summary with property and asset counts
CREATE OR REPLACE VIEW website_summary AS
SELECT
  pw.id,
  pw.property_id,
  p.name as property_name,
  pw.generation_status,
  pw.generation_progress,
  pw.brand_source,
  pw.brand_confidence,
  pw.wp_url,
  pw.version,
  COALESCE(jsonb_array_length(pw.pages_generated), 0) as pages_count,
  COUNT(DISTINCT wa.id) as assets_count,
  pw.created_at,
  pw.updated_at
FROM property_websites pw
JOIN properties p ON p.id = pw.property_id
LEFT JOIN website_assets wa ON wa.website_id = pw.id
GROUP BY pw.id, p.name;

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE property_websites IS 
'SiteForge generated websites with agentic system outputs. Blueprint column contains complete output from 6 specialized agents (Brand, Architecture, Design, Photo, Content, Quality).';

COMMENT ON COLUMN property_websites.blueprint IS 
'Complete SiteBlueprint from agentic orchestrator. Includes: brandContext, architecture, designSystem, photoManifest, qualityReport, and agentLogs.';

COMMENT ON COLUMN property_websites.site_blueprint_version IS 
'Increments with each edit. Used for versioning and rollback.';

COMMENT ON TABLE siteforge_blueprint_versions IS 
'Version history for conversational editing. Allows rollback and A/B testing.';

COMMENT ON TABLE website_assets IS 
'Media assets used in websites. Includes uploaded, BrandForge, and AI-generated photos.';

COMMENT ON COLUMN website_assets.generation_prompt IS 
'Prompt used by Photo Agent to generate this image (if source=generated).';

COMMENT ON COLUMN website_assets.quality_score IS 
'Quality rating from Photo Agent Claude Vision analysis (0-10).';

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================

-- Grant service role full access for background jobs
GRANT ALL ON property_websites TO service_role;
GRANT ALL ON website_assets TO service_role;
GRANT ALL ON siteforge_jobs TO service_role;
GRANT ALL ON siteforge_blueprint_versions TO service_role;

-- Grant authenticated users access through RLS
GRANT SELECT, INSERT, UPDATE, DELETE ON property_websites TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON website_assets TO authenticated;
GRANT SELECT ON siteforge_jobs TO authenticated;
GRANT SELECT ON siteforge_blueprint_versions TO authenticated;


